# Generated by Django 3.0.4 on 2020-08-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diceuser', '0002_diceuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diceuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
