# Generated by Django 3.0.4 on 2020-08-28 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diceuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceuser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
