# Generated by Django 3.0.3 on 2020-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diceuser', '0003_auto_20200828_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterdFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeding', models.BinaryField()),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
