# Generated by Django 3.0.3 on 2020-09-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diceuser', '0004_registerdface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterdFace',
        ),
    ]
