# Generated by Django 3.0.3 on 2020-09-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='someone', max_length=20)),
                ('profile', models.ImageField(upload_to='')),
                ('embeding', models.BinaryField()),
                ('is_registerd', models.BooleanField(default=False)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registerd_faces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
