# Generated by Django 3.0.3 on 2020-09-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='embeding',
            field=models.BinaryField(editable=True),
        ),
    ]
