# Generated by Django 3.0.3 on 2020-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200917_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='face',
            name='embeding',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='face',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
