# Generated by Django 3.1 on 2020-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200920_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='embeding',
            new_name='embedding',
        ),
    ]
